name: Publish versioned release
on:
  release:
    types:
      - published

jobs:

  tests:
    name: Execute all tests
    runs-on: ubuntu-latest
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: 🏗️ Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 🏗️ Install packages
        run: npm ci

      - name: 🏗️ Prepare environment file
        run: cp Env.template Env.ts


      - name: ✅ Execute tests
        run: npm run test

  release:
    name: Create application release version
    runs-on: ubuntu-latest
    needs:
      - tests
    permissions:
      contents: write
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: 🏗️ Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 🏗️ Setup git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: 🏷️ Set and commit release version
        id: set-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Setting version to $VERSION"
          npm version "$VERSION" --no-git-tag-version --no-commit-hooks

          git add package.json package-lock.json
          git commit -m ":bookmark: Release version $VERSION"

      - name: 🏷️ Tag release
        # This step forces the tag to ensure it has the correct version
        run: |
          VERSION="${{ steps.set-version.outputs.version }}"
          git tag -f "$VERSION" -m "Release version $VERSION"

      - name: 🔃 Push changes
        run: git push origin HEAD:main && git push origin --tags -f

  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: 🏗️ Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 🏗️ Install packages
        run: npm ci

      - name: 🏗️ Prepare environment file
        run: cp Env.template Env.ts

      - name: ⚙️ Build application
        run: npm run build

      - name: 🗄️ Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: nuxt
          path: .output
          retention-days: 1
          include-hidden-files: true

  image:
    name: Build container image
    runs-on: ubuntu-latest
    needs:
      - build-release
    permissions:
      contents: read
      packages: write
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: 🗄️ Download artifact
        uses: actions/download-artifact@v8
        with:
          name: nuxt
          path: .output

      - name: ℹ️ Generate OCI meta info
        id: docker-meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/poeschl/lan-info-page
          tags: type=ref,event=tag

      - name: 🏗️ Install qemu dependency
        uses: docker/setup-qemu-action@v4

      - name: ⚙️ Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v3
        with:
          containerfiles: docker/Dockerfile
          context: .
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          # Disable layer caching
          layers: false

      - name: 🔑 GHCR Login
        uses: redhat-actions/podman-login@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Push images
        id: push-image
        uses: redhat-actions/push-to-registry@v3
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}

      - name: 📢 Print images summary
        run: |
          echo "## Build and pushed images" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.push-image.outputs.registry-paths }}' >> $GITHUB_STEP_SUMMARY

  prepare-next-release:
    name: Prepare next dev version
    runs-on: ubuntu-latest
    needs:
      - release
    permissions:
      contents: write
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
          ref: ${{ github.ref }}

      - name: 🏗️ Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 🏗️ Setup git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: 🏷️ Set dev version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}-dev"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Setting version to $VERSION"
          npm version $VERSION --no-git-tag-version --no-commit-hooks

          git add package.json package-lock.json
          git commit -m ":bookmark: Prepare dev version $VERSION"

      - name: 🔃 Push changes
        run: git push origin HEAD:main
